steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: 
  - 'build'
  - '-t'
  - 'gcr.io/$PROJECT_ID/a24-film-scraper:$COMMIT_SHA'
  - './pipelines/a24-film-scraper'
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/a24-film-scraper:$COMMIT_SHA']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  - 'a24-film-scraper'
  - '--image'
  - 'gcr.io/$PROJECT_ID/a24-film-scraper:$COMMIT_SHA'
  - '--region'
  - 'us-central1'
images:
- 'gcr.io/$PROJECT_ID/a24-film-scraper:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY
