steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - gcloud
  - functions
  - deploy
  - wiki-film-scraper
  - --region=us-east1
  - --source=wiki-film-scraper
  - --trigger-topic=weekly-monday-jobs
  - --runtime=python310
  - --entry-point=subscribe

options:
  logging: CLOUD_LOGGING_ONLY